In [1]:
import pandas as pd
import numpy as np 
df=pd.read_csv("iris (1).csv") 
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [2]:
x=df[['sepal_length','sepal_width','petal_length','petal_width']] 
y=df[['species']] 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=410)
x_train

     sepal_length  sepal_width  petal_length  petal_width
59            5.2          2.7           3.9          1.4
0             5.1          3.5           1.4          0.2
60            5.0          2.0           3.5          1.0
93            5.0          2.3           3.3          1.0
103           6.3          2.9           5.6          1.8
..            ...          ...           ...          ...
134           6.1          2.6           5.6          1.4
145           6.7          3.0           5.2          2.3
140           6.7          3.1           5.6          2.4
37            4.9          3.6           1.4          0.1
58            6.6          2.9           4.6          1.3

[120 rows x 4 columns]

In [3]:
x_test

     sepal_length  sepal_width  petal_length  petal_width
57            4.9          2.4           3.3          1.0
10            5.4          3.7           1.5          0.2
1             4.9          3.0           1.4          0.2
124           6.7          3.3           5.7          2.1
112           6.8          3.0           5.5          2.1
86            6.7          3.1           4.7          1.5
2             4.7          3.2           1.3          0.2
131           7.9          3.8           6.4          2.0
15            5.7          4.4           1.5          0.4
79            5.7          2.6           3.5          1.0
116           6.5          3.0           5.5          1.8
88            5.6          3.0           4.1          1.3
36            5.5          3.5           1.3          0.2
147           6.5          3.0           5.2          2.0
40            5.0          3.5           1.3          0.3
92            5.8          2.6           4.0          1.2
84            5.4          3.0           4.5          1.5
130           7.4          2.8           6.1          1.9
32            5.2          4.1           1.5          0.1
53            5.5          2.3           4.0          1.3
38            4.4          3.0           1.3          0.2
117           7.7          3.8           6.7          2.2
118           7.7          2.6           6.9          2.3
81            5.5          2.4           3.7          1.0
74            6.4          2.9           4.3          1.3
22            4.6          3.6           1.0          0.2
113           5.7          2.5           5.0          2.0
97            6.2          2.9           4.3          1.3
110           6.5          3.2           5.1          2.0
91            6.1          3.0           4.6          1.4

In [4]:
x_train

     sepal_length  sepal_width  petal_length  petal_width
59            5.2          2.7           3.9          1.4
0             5.1          3.5           1.4          0.2
60            5.0          2.0           3.5          1.0
93            5.0          2.3           3.3          1.0
103           6.3          2.9           5.6          1.8
..            ...          ...           ...          ...
134           6.1          2.6           5.6          1.4
145           6.7          3.0           5.2          2.3
140           6.7          3.1           5.6          2.4
37            4.9          3.6           1.4          0.1
58            6.6          2.9           4.6          1.3

[120 rows x 4 columns]

In [5]:
y_test

        species
57   versicolor
10       setosa
1        setosa
124   virginica
112   virginica
86   versicolor
2        setosa
131   virginica
15       setosa
79   versicolor
116   virginica
88   versicolor
36       setosa
147   virginica
40       setosa
92   versicolor
84   versicolor
130   virginica
32       setosa
53   versicolor
38       setosa
117   virginica
118   virginica
81   versicolor
74   versicolor
22       setosa
113   virginica
97   versicolor
110   virginica
91   versicolor

In [6]:
y_train

        species
59   versicolor
0        setosa
60   versicolor
93   versicolor
103   virginica
..          ...
134   virginica
145   virginica
140   virginica
37       setosa
58   versicolor

[120 rows x 1 columns]

In [9]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)

DecisionTreeClassifier()

In [10]:
y_pred=dtc.predict(x_test) 
y_pred

array(['virginica', 'setosa', 'setosa', 'virginica', 'virginica',
       'versicolor', 'setosa', 'virginica', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'setosa', 'virginica', 'setosa',
       'versicolor', 'versicolor', 'virginica', 'setosa', 'versicolor',
       'setosa', 'virginica', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'virginica', 'versicolor', 'virginica', 'versicolor'],
      dtype=object)

In [11]:
from sklearn.metrics import accuracy_score,r2_score,classification_report,confusion_matrix 
acc=accuracy_score(y_test,y_pred) 
print('accuracy_score:',acc)

accuracy_score: 0.9666666666666667

In [12]:
cm=confusion_matrix(y_test,y_pred)
print('confusion_matrix:\n',cm)
cr=classification_report(y_test,y_pred)
print('classification_report:',cr)

confusion_matrix:
 [[ 9  0  0]
 [ 0 10  1]
 [ 0  0 10]]
classification_report:               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00         9
  versicolor       1.00      0.91      0.95        11
   virginica       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30